///|
pub let black : Color = RGB(0, 0, 0)

///|
pub let white : Color = RGB(255, 255, 255)

///|
pub let transparent : Color = Transparent

///|
pub let dft_line_type : LineType = Solid(1)

///|
pub let dft_line_style : LineStyle = LineStyle(dft_line_type, black)

///|
pub let dft_scatter_type : ScatterType = Circle(3)

///|
pub let dft_scatter_style : ScatterStyle = ScatterStyle(dft_scatter_type, black)

///|
pub let dft_bar_style : BarStyle = BarStyle(1, black, black)

///|
pub let dft_font : String = "Times New Roman"

///|
pub let dft_text_style : TextStyle = TextStyle(12, dft_font, black)

///|
pub let dft_title_style : TextStyle = TextStyle(16, dft_font, black)
